name: 构建并部署 Color Picker

on:
  push:
    branches:
      - 'release'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 构建项目
        run: npm run build
      
      - name: 设置 SSH 密钥
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: 添加服务器到已知主机
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: 检查 SSH 连接
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "检查 SSH 连接"
          if ! ssh -q "${SERVER_USER}@${SERVER_IP}" "exit"; then
            echo "错误: 无法连接到服务器，请检查SSH密钥和用户名/IP设置"
            exit 1
          fi
          echo "SSH 连接成功"
      
      - name: 设置部署路径
        id: set-path
        run: |
          echo "DEPLOY_PATH=/var/www/colorpicker" >> $GITHUB_OUTPUT
      
      - name: 压缩构建文件
        run: |
          cd dist
          tar -czf ../dist.tar.gz .
          cd ..
          echo "构建文件已压缩为 dist.tar.gz"
      
      - name: 部署到服务器
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: ${{ steps.set-path.outputs.DEPLOY_PATH }}
        run: |
          echo "上传压缩文件到服务器"
          if ! scp dist.tar.gz "${SERVER_USER}@${SERVER_IP}:/tmp/dist.tar.gz"; then
            echo "错误: 文件上传失败"
            exit 1
          fi
          
          echo "在服务器上解压文件并部署"
          if ! ssh "${SERVER_USER}@${SERVER_IP}" "sudo rm -rf ${DEPLOY_PATH}/* && \
            sudo mkdir -p ${DEPLOY_PATH} && \
            sudo tar -xzf /tmp/dist.tar.gz -C ${DEPLOY_PATH} && \
            sudo chown -R www-data:www-data ${DEPLOY_PATH} && \
            sudo rm -f /tmp/dist.tar.gz && \
            echo '部署完成'"; then
            echo "错误: 服务器部署失败"
            exit 1
          fi 